Added enthusiasm
chairmanlu/Universal-Turing-Machine pull request #11
Opened 2021-06-03 00:26 UTC by vchowdhary

### What you did
Added enthusiasm

### Tests
None needed

### Unresolved issues
Steven sucks

2021-06-03 00:30 UTC, chairmanlu commented on src/driver.ml
> +let () = Printf.printf "Driver!!\n"
This dum why u do dis.

2021-06-03 00:36 UTC, chairmanlu requested changes
210 > 251

2021-06-03 00:36 UTC, chairmanlu commented on src/driver.ml
> -let () = Printf.printf "Driver\n"
My code is perfect don't delete.

2021-06-03 00:36 UTC, chairmanlu commented on src/driver.ml
> +let () = Printf.printf "Driver!!\n"
```suggestion
let () = Printf.printf "Driver\n"
```

2021-06-03 00:36 UTC, chairmanlu commented on src/driver.ml
> +let () = Printf.printf "Driver!!\n"
I am smart u are dum

2021-06-03 00:37 UTC, vchowdhary commented on src/driver.ml
> +let () = Printf.printf "Driver!!\n"
you suck

2021-06-03 00:38 UTC, vchowdhary commented on src/driver.ml
> +let () = Printf.printf "Driver!!\n"
```suggestion
let () = Printf.printf "Driver!\n"
```
I like this better. WDYT?

2021-06-03 00:41 UTC, chairmanlu approved these changes
Ur still dum

2021-06-03 00:41 UTC, merged

2021-06-04 04:48 UTC, shiftsayan commented
> 210 > 251

hmmm